background_opacity 0.8
background_blur 20
term xterm-256color

enable_audio_bell no

font_family Ubuntu Mono
font_size 11.0
disable_ligatures always
bold_font auto
italic_font auto
bold_italic_font auto

cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

scrollback_lines 5000
wheel_scroll_multiplier 3.0
mouse_hide_wait -1
copy_on_select yes

remember_window_size no
initial_window_width 900
initial_window_height 550
window_border_width 1pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no

# window management 
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# tab bar customization
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style normal
inactive_tab_font_style normal

# tab management
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

# pencil dark
background            #202020
foreground            #f0f0f0
cursor                #20bafb
selection_background  #b6d6fc
color0                #202020
color8                #414141
color1                #c30670
color9                #fb0079
color2                #10a778
color10               #5ed6ae
color3                #a79c14
color11               #f3e42f
color4                #008ec4
color12               #20bafb
color5                #523b78
color13               #6854de
color6                #20a4b9
color14               #4fb8cc
color7                #d9d9d9
color15               #f0f0f0
selection_foreground  #202020

url_color #458588
active_border_color #8ec07c
inactive_border_color #665c54
active_tab_foreground #444444
active_tab_background #e3e8ed
inactive_tab_foreground #d2d8d9
inactive_tab_background #222325
