[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size" # "size"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "{cwd}"

[preview]
max_height = 1200
max_width = 1200

[tasks]
image_bound = [ 20000, 20000 ]

[plugin]
prepend_previewers = [
    { mime = "audio/*",   run = "exifaudio"}
]
