vim.o.termguicolors = true
vim.cmd('hi clear')

local c = {
  none     = 'NONE',
  line     = '#1D1D1D', -- cursorline / statusline / pmenu
  visual   = '#282828', -- selections
  alt      = '#C3C3D0',
  fg       = '#A2A2AD',
  comment  = '#4c4c57',
  constant = '#b5b3a5',
  func     = '#626E85',
  keyword  = '#7a8aa6',
  number   = '#b39066',
  operator = '#575D70',
  property = '#817882',
  string   = '#777d77',
  type     = '#6d748c',
  todo     = '#6E6E79',
  diag_red      = '#DC827B',
  diag_blue     = '#849EE1',
  diag_yellow   = '#AF9974',
  diag_green    = '#69896F',
  diff_add      = '#2E3830',
  diff_change   = '#2B303E',
  diff_delete   = '#65413E',
  diff_text     = '#202329',
  comment_error = '#A26C6D',
  comment_warn  = '#877A68',
  comment_note  = '#6E7DAA',
}

local groups = {
  -- editor
  Normal       = { fg = c.fg },
  NormalNC     = { link = 'Normal' },
  NormalFloat  = { link = 'Normal' },
  FloatBorder  = { fg = c.operator },
  FloatTitle   = { fg = c.comment,  bg = c.line },
  Conceal      = { fg = c.func },
  EndOfBuffer  = { fg = c.operator },
  NonText      = { fg = c.comment },
  Whitespace   = { fg = c.comment },
  SpecialKey   = { fg = c.comment },
  Cursor       = { reverse = true },
  CursorLine   = { bg = c.line },
  CursorColumn = { bg = c.line },
  ColorColumn  = { bg = c.line },
  CursorLineNr = { fg = c.fg },
  LineNr       = { fg = c.comment },
  SignColumn   = { fg = c.fg },
  FoldColumn   = { fg = c.comment },
  Folded       = { fg = c.comment,  bg = c.line },
  WinSeparator = { fg = c.operator },
  MatchParen   = { fg = c.fg,       bg = c.visual, bold = true },
  Directory    = { fg = c.keyword },
  Title        = { fg = c.keyword,  bold = true },
  ModeMsg      = { fg = c.fg,       bold = true },
  MoreMsg      = { fg = c.func,     bold = true },
  Question     = { fg = c.constant },
  ErrorMsg     = { fg = c.diag_red,    bold = true },
  WarningMsg   = { fg = c.diag_yellow, bold = true },
  MsgSeparator = { fg = c.string, bg = c.line, bold = true },

  -- search / selection
  Visual     = { fg = c.alt,  bg = c.visual },
  Search     = { fg = c.alt,  bg = c.visual },
  IncSearch  = { fg = c.type, bg = c.visual },
  CurSearch  = { link = 'IncSearch' },
  Substitute = { link = 'IncSearch' },

  -- popup menu (kept solid for readability over a transparent bg)
  Pmenu      = { fg = c.comment, bg = c.line },
  PmenuSel   = { fg = c.alt,     bg = c.visual },
  PmenuSbar  = { bg = c.line },
  PmenuThumb = { bg = c.visual },
  WildMenu   = { fg = c.alt,     bg = c.visual },

  -- statusline / tabline
  StatusLine   = { fg = c.fg, bg = c.line },
  StatusLineNC = { link = 'StatusLine' },
  TabLine      = { fg = c.comment, bg = c.line },
  TabLineFill  = { fg = c.comment, bg = c.line },
  TabLineSel   = { fg = c.alt,     bg = c.visual },

  -- syntax
  Comment     = { fg = c.comment },
  Constant    = { fg = c.constant },
  String      = { fg = c.string },
  Character   = { link = 'String' },
  Number      = { fg = c.number },
  Float       = { link = 'Number' },
  Boolean     = { link = 'Number' },
  Identifier  = { fg = c.property },
  Function    = { fg = c.func },
  Statement   = { fg = c.keyword },
  Keyword     = { link = 'Statement' },
  Conditional = { link = 'Statement' },
  Operator    = { fg = c.operator },
  PreProc     = { fg = c.string },
  Include     = { fg = c.constant },
  Macro       = { fg = c.number, italic = true },
  Type        = { fg = c.type },
  Special     = { fg = c.type },
  SpecialChar = { fg = c.keyword },
  Delimiter   = { fg = c.fg },
  Error       = { fg = c.diag_red },
  Exception   = { link = 'Error' },
  Todo        = { fg = c.todo, bold = true, italic = true },

  -- diagnostics
  DiagnosticError = { fg = c.diag_red },
  DiagnosticWarn  = { fg = c.diag_yellow },
  DiagnosticInfo  = { fg = c.diag_blue, italic = true },
  DiagnosticHint  = { fg = c.diag_blue },
  DiagnosticVirtualTextError = { link = 'DiagnosticError' },
  DiagnosticVirtualTextWarn  = { link = 'DiagnosticWarn' },
  DiagnosticVirtualTextInfo  = { fg = c.diag_blue },
  DiagnosticVirtualTextHint  = { link = 'DiagnosticHint' },
  DiagnosticUnderlineError = { undercurl = true, sp = c.diag_red },
  DiagnosticUnderlineWarn  = { undercurl = true, sp = c.diag_yellow },
  DiagnosticUnderlineInfo  = { undercurl = true, sp = c.diag_blue },
  DiagnosticUnderlineHint  = { undercurl = true, sp = c.diag_blue },
  SpellBad   = { undercurl = true, sp = c.diag_red },
  SpellCap   = { undercurl = true, sp = c.diag_yellow },
  SpellLocal = { undercurl = true, sp = c.diag_blue },
  SpellRare  = { undercurl = true, sp = c.diag_blue },

  -- diff (subtle solid backgrounds)
  DiffAdd    = { bg = c.diff_add },
  DiffChange = { bg = c.diff_change },
  DiffDelete = { bg = c.diff_delete },
  DiffText   = { fg = c.diag_blue, bg = c.diff_text },

  -- treesitter
  ['@variable']            = { fg = c.fg },
  ['@variable.builtin']    = { fg = c.type },
  ['@variable.member']     = { fg = c.property },
  ['@variable.parameter']  = { fg = c.alt },
  ['@constant.builtin']    = { fg = c.type },
  ['@module']              = { fg = c.type },
  ['@constructor.lua']     = { fg = c.alt },
  ['@keyword']             = { fg = c.keyword },
  ['@punctuation.delimiter'] = { fg = c.fg },
  ['@punctuation.bracket']   = { fg = c.operator },
  ['@markup.heading']      = { fg = c.keyword },
  ['@markup.strong']       = { fg = c.fg, bold = true },
  ['@markup.italic']       = { fg = c.fg, italic = true },
  ['@markup.link.uri']     = { fg = c.alt, underline = true },
  ['@markup.link']         = { fg = c.type },
  ['@markup.raw']          = { fg = c.func },
  ['@markup.list']         = { fg = c.func },
  ['@diff.plus']           = { fg = c.diag_green },
  ['@diff.minus']          = { fg = c.diag_red },
  ['@diff.delta']          = { fg = c.diag_blue },
  ['@tag.delimiter']       = { fg = c.fg },
  ['@comment.error']       = { fg = c.comment_error, bold = true, italic = true },
  ['@comment.warning']     = { fg = c.comment_warn,  bold = true, italic = true },
  ['@comment.note']        = { fg = c.comment_note,  bold = true, italic = true },

  -- gitsigns
  GitSignsAdd    = { fg = c.diag_green },
  GitSignsChange = { fg = c.diag_blue },
  GitSignsDelete = { fg = c.diag_red },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end
